export const DATA = [
  {
    id: 1,
    isFavourited: false,
    english: 'Cheers',
    creole: 'Sante; a sa sante',
  },
  { id: 2, isFavourited: false, english: 'Please', creole: 'Silvouple' },
  { id: 3, isFavourited: false, english: 'Thank you', creole: 'Mersi' },
  { id: 4, isFavourited: false, english: 'Excuse me', creole: 'Ekskize' },
  {
    id: 5,
    isFavourited: false,
    english: 'Excuse me, please',
    creole: 'Elokiz mwan, silvouple',
  },
  {
    id: 6,
    isFavourited: false,
    english: "I'm fine, thanks",
    creole: 'Mon byen, mersi',
  },
  {
    id: 7,
    isFavourited: false,
    english: 'Very well, thanks',
    creole: 'Tre byen, mersi',
  },
  { id: 8, isFavourited: false, english: 'Not too bad', creole: 'Pa tro mal' },
  { id: 9, isFavourited: false, english: 'How much?', creole: 'Konbyen?' },
  { id: 10, isFavourited: false, english: 'How?', creole: 'Koman?' },
  { id: 11, isFavourited: false, english: 'Where?', creole: 'Oli?' },
  { id: 12, isFavourited: false, english: 'Why?', creole: 'Akoz?' },
  { id: 13, isFavourited: false, english: 'When?', creole: 'Kan?' },
  { id: 14, isFavourited: false, english: 'Who?', creole: 'Lekel, ki?' },
  { id: 15, isFavourited: false, english: 'What?', creole: 'Kwa?' },
  { id: 16, isFavourited: false, english: "What's that?", creole: 'Kisisa' },
  {
    id: 17,
    isFavourited: false,
    english: 'What do you call that?',
    creole: 'Ki mannyer sa i apele',
  },
  {
    id: 18,
    isFavourited: false,
    english: 'How do you say?',
    creole: 'Ki mannyer ou dir?',
  },
  {
    id: 19,
    isFavourited: false,
    english: "What's your name?",
    creole: 'Ki mannyer ou apele?',
  },
  {
    id: 20,
    isFavourited: false,
    english: "What's his name?",
    creole: 'Ki mannyer i apele?',
  },
  {
    id: 21,
    isFavourited: false,
    english: 'How old are you?',
    creole: 'Ki laz ou annan?',
  },
  {
    id: 22,
    isFavourited: false,
    english: 'Do you understand?',
    creole: 'Eski ou konpran?',
  },
  {
    id: 23,
    isFavourited: false,
    english: 'Where are you going?',
    creole: 'Kot ou pe ale?',
  },
  {
    id: 24,
    isFavourited: false,
    english: 'Where do you live/work?',
    creole: 'Kote ou reste/travay',
  },
  {
    id: 25,
    isFavourited: false,
    english: 'What do you do on Sunday?',
    creole: 'Ki ou fer dan Dimans?',
  },
  {
    id: 26,
    isFavourited: false,
    english: 'What do you say?',
    creole: 'Ki ou dir?',
  },
  {
    id: 27,
    isFavourited: false,
    english: 'What do you want?',
    creole: 'Ki ou oule?',
  },
  {
    id: 28,
    isFavourited: false,
    english: 'What time is it?',
    creole: 'Ki ler i ete? Kel er?',
  },
  { id: 29, isFavourited: false, english: 'Where is ...?', creole: 'Kote...?' },
  {
    id: 30,
    isFavourited: false,
    english: 'Is it far from here?',
    creole: 'Eski i lwen?',
  },
  {
    id: 31,
    isFavourited: false,
    english: 'Can we walk up there?',
    creole: 'Eski nou kapab al laba apye?',
  },
  {
    id: 32,
    isFavourited: false,
    english: 'Could you repeat, please?',
    creole: 'Eski ou kapab repet sa silvouple',
  },
  {
    id: 33,
    isFavourited: false,
    english: 'Is there ... nearby?',
    creole: 'Eski i annan par isi?',
  },
  { id: 34, isFavourited: false, english: 'a bus stop?', creole: 'en bestop?' },
  {
    id: 35,
    isFavourited: false,
    english: 'a public toilet?',
    creole: 'bann twalet piblik?',
  },
  {
    id: 36,
    isFavourited: false,
    english: 'a restaurant?',
    creole: 'en restoran?',
  },
  {
    id: 37,
    isFavourited: false,
    english: 'a taxi stand?',
    creole: 'en taksi stenn?',
  },
  { id: 38, isFavourited: false, english: 'a bank?', creole: 'en labank?' },
  {
    id: 39,
    isFavourited: false,
    english: 'an exchange bureau',
    creole: 'en biro lesanz',
  },
  {
    id: 40,
    isFavourited: false,
    english: 'a shop, a store?',
    creole: 'en laboutik?',
  },
  {
    id: 41,
    isFavourited: false,
    english: 'a post office?',
    creole: 'en lapos?',
  },
  {
    id: 42,
    isFavourited: false,
    english: 'a petrol station?',
    creole: 'laponp bennzin?',
  },
  {
    id: 43,
    isFavourited: false,
    english: 'a clinic, hospital?',
    creole: 'en klinik, lopital?',
  },
  { id: 44, isFavourited: false, english: 'a market?', creole: 'en bazar?' },
  {
    id: 45,
    isFavourited: false,
    english: 'a tourist office?',
    creole: 'lofis touris?',
  },
  {
    id: 46,
    isFavourited: false,
    english: 'a travel agency?',
    creole: 'en lazans vwayaz?',
  },
  {
    id: 47,
    isFavourited: false,
    english: 'a hairdresser?',
    creole: 'en kwafer?',
  },
  { id: 48, isFavourited: false, english: 'a dentist?', creole: 'en dantis?' },
  {
    id: 49,
    isFavourited: false,
    english: 'a police station?',
    creole: 'en stasyon lapolis?',
  },
  { id: 50, isFavourited: false, english: 'Yes', creole: 'Wi' },
  {
    id: 51,
    isFavourited: false,
    english: 'Alright, O.K.',
    creole: 'Oke, dakor',
  },
  { id: 52, isFavourited: false, english: 'Perhaps, maybe', creole: 'Petet' },
  { id: 53, isFavourited: false, english: 'It is true', creole: 'I vre' },
  { id: 54, isFavourited: false, english: 'No', creole: 'Non' },
  { id: 55, isFavourited: false, english: 'Never', creole: 'Zanmen' },
  {
    id: 56,
    isFavourited: false,
    english: 'Nobody, none',
    creole: 'Napa personn',
  },
  { id: 57, isFavourited: false, english: 'Nothing', creole: 'Nanryen' },
  {
    id: 58,
    isFavourited: false,
    english: 'It is false, untrue',
    creole: 'I fo, pa vre',
  },
  {
    id: 59,
    isFavourited: false,
    english: 'It is impossible',
    creole: 'I enposib',
  },
  {
    id: 60,
    isFavourited: false,
    english: 'I do not understand',
    creole: 'Mon pa konpran',
  },
  {
    id: 61,
    isFavourited: false,
    english: "I don't know",
    creole: 'Mon pa konnen',
  },
  { id: 62, isFavourited: false, english: 'Sir, Mister', creole: 'Msye,' },
  { id: 63, isFavourited: false, english: 'Madam', creole: 'Madanm' },
  {
    id: 64,
    isFavourited: false,
    english: 'Miss',
    creole: 'Mademwazel, Mis, Manmzel',
  },
  {
    id: 65,
    isFavourited: false,
    english: 'Ladies, Gentlemen',
    creole: 'Msye, madanm',
  },
  { id: 66, isFavourited: false, english: 'Good morning', creole: 'Bonzour' },
  { id: 67, isFavourited: false, english: 'Hello', creole: 'Alo' },
  { id: 68, isFavourited: false, english: 'Good evening', creole: 'Bonswar' },
  { id: 69, isFavourited: false, english: 'Good night', creole: 'Bonn nwit' },
  { id: 70, isFavourited: false, english: 'Goodbye', creole: 'Orevwar' },
  {
    id: 71,
    isFavourited: false,
    english: 'See you tomorrow',
    creole: 'A demen',
  },
  {
    id: 72,
    isFavourited: false,
    english: "I'm very pleased...",
    creole: 'Mon byen kontan...',
  },
  {
    id: 73,
    isFavourited: false,
    english: 'My name is Mr, Mrs X',
    creole: 'Mon apel Msye, Mme Iks',
  },
  {
    id: 74,
    isFavourited: false,
    english: 'How do you do?',
    creole: 'Koman ou sava? / Ki nouvel?',
  },
  { id: 75, isFavourited: false, english: 'How are you?', creole: 'Ki i dir?' },
  {
    id: 76,
    isFavourited: false,
    english: 'What is your name?',
    creole: 'Ki mannyer ou apele?',
  },
  { id: 77, isFavourited: false, english: 'To be', creole: 'Ete' },
  { id: 78, isFavourited: false, english: 'To do', creole: 'Fer' },
  { id: 79, isFavourited: false, english: 'To have', creole: 'Annan' },
  { id: 80, isFavourited: false, english: 'To go', creole: 'Ale' },
  { id: 81, isFavourited: false, english: 'To come', creole: 'Vini' },
  {
    id: 82,
    isFavourited: false,
    english: 'To come in, enter',
    creole: 'Antre',
  },
  { id: 83, isFavourited: false, english: 'To go away', creole: 'Ale' },
  { id: 84, isFavourited: false, english: 'To go back', creole: 'Retournen' },
  { id: 85, isFavourited: false, english: 'To go forward', creole: 'Avanse' },
  { id: 86, isFavourited: false, english: 'To look for', creole: 'Rod, sers' },
  { id: 87, isFavourited: false, english: 'To find', creole: 'Gannyen' },
  { id: 88, isFavourited: false, english: 'To get', creole: 'Gannyen' },
  {
    id: 89,
    isFavourited: false,
    english: 'To go downstairs',
    creole: 'Desann',
  },
  { id: 90, isFavourited: false, english: 'To go out, exit', creole: 'Sorti' },
  { id: 91, isFavourited: false, english: 'To go up', creole: 'Monte' },
  { id: 92, isFavourited: false, english: 'To stand up', creole: 'Leve' },
  {
    id: 93,
    isFavourited: false,
    english: 'To get up, from bed',
    creole: 'Leve',
  },
  { id: 94, isFavourited: false, english: 'To arrive', creole: 'Arive' },
  {
    id: 95,
    isFavourited: false,
    english: 'To leave, depart, happen',
    creole: 'Arive',
  },
  { id: 96, isFavourited: false, english: 'To run', creole: 'Kouri' },
  { id: 97, isFavourited: false, english: 'To walk', creole: 'Marse' },
  { id: 98, isFavourited: false, english: 'To sit (down)', creole: 'Asize' },
  {
    id: 99,
    isFavourited: false,
    english: 'To speak (say)',
    creole: 'Dir, koze',
  },
  { id: 100, isFavourited: false, english: 'To listen', creole: 'Ekoute' },
  { id: 101, isFavourited: false, english: 'To wash', creole: 'Lave' },
  { id: 102, isFavourited: false, english: 'To ask', creole: 'Demande' },
  { id: 103, isFavourited: false, english: 'To answer', creole: 'Reponn' },
  { id: 104, isFavourited: false, english: 'To eat', creole: 'Manze' },
  { id: 105, isFavourited: false, english: 'To drink', creole: 'Bwar' },
  {
    id: 106,
    isFavourited: false,
    english: 'To put on, switch off',
    creole: 'Tannyen',
  },
  { id: 107, isFavourited: false, english: 'To buy', creole: 'Aste' },
  { id: 108, isFavourited: false, english: 'To cook', creole: 'Kwi' },
  { id: 109, isFavourited: false, english: 'To watch', creole: 'Veye' },
  { id: 110, isFavourited: false, english: 'To sleep', creole: 'Dormi' },
  { id: 111, isFavourited: false, english: 'To read', creole: 'Lir' },
  { id: 112, isFavourited: false, english: 'To write', creole: 'Ekrir' },
  {
    id: 113,
    isFavourited: false,
    english: 'To place, to wear',
    creole: 'Mete',
  },
  { id: 114, isFavourited: false, english: 'To like', creole: 'Kontan' },
  { id: 115, isFavourited: false, english: 'To love', creole: 'Kontan' },
  { id: 116, isFavourited: false, english: 'To want', creole: 'Oule' },
  { id: 117, isFavourited: false, english: 'To wish', creole: 'Swe' },
  { id: 118, isFavourited: false, english: 'To use', creole: 'Servi' },
  { id: 119, isFavourited: false, english: 'To smoke', creole: 'Fimen' },
  { id: 120, isFavourited: false, english: 'To see', creole: 'Vwar' },
  { id: 121, isFavourited: false, english: 'To feel', creole: 'Santi' },
  { id: 122, isFavourited: false, english: 'To tidy', creole: 'Ranze' },
  { id: 123, isFavourited: false, english: 'To fall', creole: 'Tonbe' },
  { id: 124, isFavourited: false, english: 'To close, shut', creole: 'Fermen' },
  { id: 125, isFavourited: false, english: 'To open', creole: 'Ouver' },
  {
    id: 126,
    isFavourited: false,
    english: 'To wash (dishes, etc)',
    creole: 'Fesel',
  },
  {
    id: 127,
    isFavourited: false,
    english: 'To play (games, music)',
    creole: 'Zwe',
  },
  { id: 128, isFavourited: false, english: 'To hurry', creole: 'Dpese' },
  { id: 129, isFavourited: false, english: 'To cry', creole: 'Plere' },
  { id: 130, isFavourited: false, english: 'To swim', creole: 'Naze' },
  {
    id: 131,
    isFavourited: false,
    english: 'To come back, to return',
    creole: 'Retournen',
  },
  { id: 132, isFavourited: false, english: 'To go out', creole: 'Sorti' },
  { id: 133, isFavourited: false, english: 'To fall (down)', creole: 'Tonbe' },
  {
    id: 134,
    isFavourited: false,
    english: 'To dress, get dressed',
    creole: 'Abiye',
  },
  { id: 135, isFavourited: false, english: 'To fill', creole: 'Ranpli' },
  { id: 136, isFavourited: false, english: 'To comb', creole: 'Peny-en' },
  { id: 137, isFavourited: false, english: 'To count', creole: 'Konte' },
  { id: 138, isFavourited: false, english: 'To clean', creole: 'Netwaye' },
  { id: 139, isFavourited: false, english: 'To cut', creole: 'Koupe' },
  { id: 140, isFavourited: false, english: 'To build', creole: 'Konstri' },
  { id: 141, isFavourited: false, english: 'To mend', creole: 'Ranz, repare' },
  { id: 142, isFavourited: false, english: 'To talk', creole: 'Koz, koze' },
  { id: 143, isFavourited: false, english: 'To tell', creole: 'Rakonte' },
  { id: 144, isFavourited: false, english: 'To accept', creole: 'Aksepte' },
  { id: 145, isFavourited: false, english: 'To agree', creole: 'Dakor' },
  {
    id: 146,
    isFavourited: false,
    english: 'To argue',
    creole: 'Diskit, lager',
  },
  { id: 147, isFavourited: false, english: 'To believe', creole: 'Krwar' },
  { id: 148, isFavourited: false, english: 'To dance', creole: 'Danse' },
  { id: 149, isFavourited: false, english: 'To sing', creole: 'Sante' },
  {
    id: 150,
    isFavourited: false,
    english: 'To forbid, prohibit',
    creole: 'Defann',
  },
  { id: 151, isFavourited: false, english: 'To give', creole: 'Donn' },
  { id: 152, isFavourited: false, english: 'To help', creole: 'Ede' },
  { id: 153, isFavourited: false, english: 'To invite', creole: 'Envite' },
  { id: 154, isFavourited: false, english: 'To know', creole: 'Konnen' },
  { id: 155, isFavourited: false, english: 'To laugh', creole: 'Riye' },
  { id: 156, isFavourited: false, english: 'To lie', creole: 'Manti' },
  { id: 157, isFavourited: false, english: 'To meet', creole: 'Zwenn' },
  { id: 158, isFavourited: false, english: 'To offer', creole: 'Ofer' },
  { id: 159, isFavourited: false, english: 'To pay', creole: 'Peye' },
  { id: 160, isFavourited: false, english: 'To promise', creole: 'Promet' },
  { id: 161, isFavourited: false, english: 'To refuse', creole: 'Refize' },
  { id: 162, isFavourited: false, english: 'To smile', creole: 'Souri' },
  { id: 163, isFavourited: false, english: 'To think', creole: 'Panse' },
  { id: 164, isFavourited: false, english: 'To try', creole: 'Esey' },
  { id: 165, isFavourited: false, english: 'To visit', creole: 'Rann vizit' },
  { id: 166, isFavourited: false, english: 'To understand', creole: 'Konpran' },
  { id: 167, isFavourited: false, english: 'To be born', creole: 'Ne' },
  { id: 168, isFavourited: false, english: 'To die', creole: 'Mor' },
  { id: 169, isFavourited: false, english: 'To live', creole: 'Reste' },
  { id: 170, isFavourited: false, english: 'To confirm', creole: 'Konfirmen' },
  { id: 171, isFavourited: false, english: 'To continue', creole: 'Kontinyen' },
  { id: 172, isFavourited: false, english: 'To decide', creole: 'Deside' },
  { id: 173, isFavourited: false, english: 'To discuss', creole: 'Diskite' },
  { id: 174, isFavourited: false, english: 'To finish', creole: 'Fini' },
  { id: 175, isFavourited: false, english: 'To marry', creole: 'Marye' },
  { id: 176, isFavourited: false, english: 'To prepare', creole: 'Prepare' },
  { id: 177, isFavourited: false, english: 'To remember', creole: 'Rapel' },
  { id: 178, isFavourited: false, english: 'To rent, hire', creole: 'Lwe' },
  { id: 179, isFavourited: false, english: 'To reserve', creole: 'Reserve' },
  { id: 180, isFavourited: false, english: 'To seem', creole: 'Sanble' },
  { id: 181, isFavourited: false, english: 'To send', creole: 'Voye' },
  { id: 182, isFavourited: false, english: 'To show', creole: 'Montre' },
  { id: 183, isFavourited: false, english: 'To start', creole: 'Koumanse' },
  { id: 184, isFavourited: false, english: 'To travel', creole: 'Vwayaze' },
  {
    id: 185,
    isFavourited: false,
    english: 'To visit (a person)',
    creole: 'Rann vizit',
  },
  {
    id: 186,
    isFavourited: false,
    english: 'To visit (a place)',
    creole: 'Vizite',
  },
  { id: 187, isFavourited: false, english: 'To have to', creole: 'Bizwen' },
  { id: 188, isFavourited: false, english: 'To be able', creole: 'Kapab' },
  { id: 189, isFavourited: false, english: 'To make', creole: 'Fer' },
  { id: 190, isFavourited: false, english: 'To take', creole: 'Pran' },
  {
    id: 191,
    isFavourited: false,
    english: 'To fetch',
    creole: 'Anmenn, anmennen',
  },
  {
    id: 192,
    isFavourited: false,
    english: 'To bring',
    creole: 'Anmenn, anmennen',
  },
  { id: 193, isFavourited: false, english: 'To know how', creole: 'Konnen' },
  { id: 194, isFavourited: false, english: 'To let', creole: 'Les' },
  { id: 195, isFavourited: false, english: 'To put', creole: 'Met' },
  { id: 196, isFavourited: false, english: 'To lose', creole: 'Perd' },
  { id: 197, isFavourited: false, english: 'To wear', creole: 'Port' },
  { id: 198, isFavourited: false, english: 'To sell', creole: 'Vann' },
  { id: 199, isFavourited: false, english: 'To look', creole: 'Get' },
  { id: 200, isFavourited: false, english: 'To hear', creole: 'Tann' },
  { id: 201, isFavourited: false, english: 'To hide', creole: 'Kasyet' },
  { id: 202, isFavourited: false, english: 'To jump', creole: 'Sote' },
  {
    id: 203,
    isFavourited: false,
    english: 'Do you have a double room?',
    creole: 'Eski ou annan en lasonm doub?',
  },
  {
    id: 204,
    isFavourited: false,
    english: 'Could you reserve a room for me?',
    creole: 'Eski ou kapab rezerv en lasonm pour mwan?',
  },
  {
    id: 205,
    isFavourited: false,
    english: 'For one night',
    creole: 'Pour enn nwit',
  },
  {
    id: 206,
    isFavourited: false,
    english: 'For one week',
    creole: 'Pour enn semenn',
  },
  {
    id: 207,
    isFavourited: false,
    english: 'Would it be possible to see the room?',
    creole: 'Eski i posib pour vwar sa lasonm?',
  },
  {
    id: 208,
    isFavourited: false,
    english: 'Would it be possible to have a room with a bath?',
    creole: 'Eski i posib pour ganny en lasonm avek beny?',
  },
  {
    id: 209,
    isFavourited: false,
    english: 'Will you have our luggage sent up?',
    creole: 'Eski ou kapab fer mont nou bagaz?',
  },
  {
    id: 210,
    isFavourited: false,
    english: 'Do you accept credit cards?',
    creole: 'Eski ou aksepte kart kredi?',
  },
  {
    id: 211,
    isFavourited: false,
    english: "What's the room number?",
    creole: 'Ki nimero sa lasonm?',
  },
  {
    id: 212,
    isFavourited: false,
    english: "I'd like to leave this in the hotel safe",
    creole: 'Mon ti a kontan kit sa dan kofor lotel',
  },
  {
    id: 213,
    isFavourited: false,
    english: 'Can you have this laundered for me?',
    creole: 'Eski ou kapab fer lav sa pour mwan?',
  },
  {
    id: 214,
    isFavourited: false,
    english: 'Can you have this ironed for me?',
    creole: 'Eski ou kapab fer repas sa pour mwan?',
  },
  {
    id: 215,
    isFavourited: false,
    english: 'At what time is the meal?',
    creole: 'Ki ler i annan manze?',
  },
  { id: 216, isFavourited: false, english: 'Lunch', creole: 'Dezenen' },
  { id: 217, isFavourited: false, english: 'Dinner', creole: 'Dinen' },
  {
    id: 218,
    isFavourited: false,
    english: "Where's the...?",
    creole: 'Oli ...?',
  },
  {
    id: 219,
    isFavourited: false,
    english: 'dining room',
    creole: 'lasal a manze',
  },
  { id: 220, isFavourited: false, english: 'toilet', creole: 'twalet' },
  { id: 221, isFavourited: false, english: 'key', creole: 'lakle' },
  { id: 222, isFavourited: false, english: 'manager', creole: 'manidzer' },
  { id: 223, isFavourited: false, english: 'porter', creole: 'porter' },
  { id: 224, isFavourited: false, english: 'waiter', creole: 'serviter' },
  { id: 225, isFavourited: false, english: 'chambermaid', creole: 'bòn' },
  { id: 226, isFavourited: false, english: 'my bill', creole: 'mon bèl' },
  {
    id: 227,
    isFavourited: false,
    english: 'my passport',
    creole: 'mon paspor',
  },
  { id: 228, isFavourited: false, english: 'my luggage', creole: 'mon bagaz' },
  { id: 229, isFavourited: false, english: 'a towel', creole: 'servièt' },
  { id: 230, isFavourited: false, english: 'a blanket', creole: 'kouvertir' },
  { id: 231, isFavourited: false, english: 'soap', creole: 'savon' },
  { id: 232, isFavourited: false, english: 'some water', creole: 'delo' },
  { id: 233, isFavourited: false, english: 'a stamp', creole: 'tenm' },
  { id: 234, isFavourited: false, english: 'an envelope', creole: 'anvlop' },
  {
    id: 235,
    isFavourited: false,
    english: "I'd like to reserve a table.",
    creole: 'Mon ti a kontan rezerv en tab.',
  },
  {
    id: 236,
    isFavourited: false,
    english: 'For one, two, three persons',
    creole: 'Pour enn, de, trwa personn.',
  },
  {
    id: 237,
    isFavourited: false,
    english: "I've already made a reservation.",
    creole: "Mon'n fini anrezistre.",
  },
  {
    id: 238,
    isFavourited: false,
    english: 'The menu, please.',
    creole: 'Meni, silvouple.',
  },
  {
    id: 239,
    isFavourited: false,
    english: 'Waiter/waitress',
    creole: 'Garson/servis.',
  },
  {
    id: 240,
    isFavourited: false,
    english: "Today's special menu.",
    creole: 'Meni pour ozordi.',
  },
  { id: 241, isFavourited: false, english: "What's this?", creole: 'Ki sa?' },
  {
    id: 242,
    isFavourited: false,
    english: "I'd like to order a rice and curry",
    creole: 'Mon ti a kontan Diri avek kari',
  },
  {
    id: 243,
    isFavourited: false,
    english: "I'd like to order fish curry",
    creole: 'Mon ti a kontan Kari pwason',
  },
  {
    id: 244,
    isFavourited: false,
    english: "I'd like to order chicken",
    creole: 'Mon ti a kontan En poul',
  },
  {
    id: 245,
    isFavourited: false,
    english: "I'd like to order Beef",
    creole: 'Mon ti a kontan Bef',
  },
  {
    id: 246,
    isFavourited: false,
    english: 'What have you got as a side-dish?',
    creole: 'Ki kalite lagarnitir ou annan?',
  },
  {
    id: 247,
    isFavourited: false,
    english: 'The bill, please.',
    creole: 'Bil, silvouple.',
  },
  {
    id: 248,
    isFavourited: false,
    english: 'Is service included?',
    creole: 'Eski servis i enkli?',
  },
  {
    id: 249,
    isFavourited: false,
    english: "I'd like to reserve a table.",
    creole: 'Mon ti a kontan rezerv en etab.',
  },
  {
    id: 250,
    isFavourited: false,
    english: 'Give me a kilo / a pound of meat',
    creole: 'Donn mwan en kilo / en liv Lavyann',
  },
  {
    id: 251,
    isFavourited: false,
    english: 'Give me a kilo / a pound of fish',
    creole: 'Donn mwan en kilo / en liv Pwason',
  },
  {
    id: 252,
    isFavourited: false,
    english: 'Give me a kilo / a pound of chicken',
    creole: 'Donn mwan en kilo / en liv Poul',
  },
  {
    id: 253,
    isFavourited: false,
    english: 'Give me a kilo / a pound of vegetables',
    creole: 'Donn mwan en kilo / en liv Brezel',
  },
  {
    id: 254,
    isFavourited: false,
    english: 'Give me a kilo / a pound of green/red chili',
    creole: 'Donn mwan en kilo / en liv Piman ver/rouz',
  },
  {
    id: 255,
    isFavourited: false,
    english: 'Give me a kilo / a pound of potatoes',
    creole: 'Donn mwan en kilo / en liv Ponmdeter',
  },
  {
    id: 256,
    isFavourited: false,
    english: 'Give me a kilo / a pound of onions',
    creole: 'Donn mwan en kilo / en liv Zonyon',
  },
  {
    id: 257,
    isFavourited: false,
    english: 'Give me a kilo / a pound of bananas',
    creole: 'Donn mwan en kilo / en liv Bannann',
  },
  {
    id: 258,
    isFavourited: false,
    english: 'I would like a cauliflower',
    creole: 'Mon ti a kontan En soufler',
  },
  {
    id: 259,
    isFavourited: false,
    english: 'I would like two coconuts',
    creole: 'Mon ti a kontan De koko',
  },
  {
    id: 260,
    isFavourited: false,
    english: 'I would like three mangoes',
    creole: 'Mon ti a kontan Trwa mang',
  },
  {
    id: 261,
    isFavourited: false,
    english: 'I would like four oranges',
    creole: 'Mon ti a kontan Kat zoranz',
  },
  {
    id: 262,
    isFavourited: false,
    english: 'I would like five apples',
    creole: 'Mon ti a kontan Senk ponm',
  },
  {
    id: 263,
    isFavourited: false,
    english: 'I would like a bunch of bananas',
    creole: 'Mon ti a kontan En lapat bannann',
  },
  {
    id: 264,
    isFavourited: false,
    english: 'I would like a bunch of parsley',
    creole: 'Mon ti a kontan En pake persi',
  },
  {
    id: 265,
    isFavourited: false,
    english: 'I would like a lettuce',
    creole: 'Mon ti a kontan En saled',
  },
  {
    id: 266,
    isFavourited: false,
    english: 'Give me that',
    creole: 'Donn mwan',
  },
  {
    id: 267,
    isFavourited: false,
    english: 'How much is that?',
    creole: 'Konbyen sa?',
  },
  {
    id: 268,
    isFavourited: false,
    english: "I'd like to send a telegram",
    creole: 'Mon ti a kontan anvoy en telegram',
  },
  {
    id: 269,
    isFavourited: false,
    english: "I'd like a postcard",
    creole: 'Mon ti a kontan en kartpostal',
  },
  {
    id: 270,
    isFavourited: false,
    english: "I'd like some stamps",
    creole: 'Mon ti a kontan detrwa tenm',
  },
  {
    id: 271,
    isFavourited: false,
    english: 'A letter/stamp for',
    creole: 'En let/tenm pour...',
  },
  {
    id: 272,
    isFavourited: false,
    english: 'A large stamp for Europe',
    creole: 'En gran tenm pour Lerop',
  },
  {
    id: 273,
    isFavourited: false,
    english: "What's the postage for a letter?",
    creole: 'Konbyen bouse pour anvoy en let?',
  },
  {
    id: 274,
    isFavourited: false,
    english: 'May I have a plastic bag',
    creole: 'Mon ti a kontan En sak plastik',
  },
  {
    id: 275,
    isFavourited: false,
    english: 'May I have some matches',
    creole: 'Mon ti a kontan En bwat lalimet',
  },
  {
    id: 276,
    isFavourited: false,
    english: 'May I have a postcard',
    creole: 'Mon ti a kontan En kartpostal',
  },
  {
    id: 277,
    isFavourited: false,
    english: 'May I have a pen/pencil',
    creole: 'Mon ti a kontan En plim/en kreon',
  },
  {
    id: 278,
    isFavourited: false,
    english: 'May I have a newspaper',
    creole: 'Mon ti a kontan En zournal',
  },
  {
    id: 279,
    isFavourited: false,
    english: 'May I have toilet paper',
    creole: 'Mon ti a kontan En papye twalet',
  },
  {
    id: 280,
    isFavourited: false,
    english: 'May I have cigarettes',
    creole: 'Mon ti a kontan En pake sigaret',
  },
  {
    id: 281,
    isFavourited: false,
    english: 'May I have some razor blades',
    creole: 'Mon ti a kontan En pake razwa',
  },
  {
    id: 282,
    isFavourited: false,
    english: 'May I have some soap',
    creole: 'Mon ti a kontan En savon',
  },
  {
    id: 283,
    isFavourited: false,
    english: 'May I have some toothpaste',
    creole: 'Mon ti a kontan En lapat dan',
  },
  {
    id: 284,
    isFavourited: false,
    english: 'May I have some sweets',
    creole: 'Mon ti a kontan En pake sirèt',
  },
  {
    id: 285,
    isFavourited: false,
    english: 'May I have a tonic water',
    creole: 'Mon ti a kontan En tonik',
  },
  {
    id: 286,
    isFavourited: false,
    english: 'May I have some orange juice',
    creole: 'Mon ti a kontan Dizi zoranz',
  },
  {
    id: 287,
    isFavourited: false,
    english: 'May I have fruit juice',
    creole: 'Mon ti a kontan Dizi frwi',
  },
  {
    id: 288,
    isFavourited: false,
    english: 'May I have mineral water',
    creole: 'Mon ti a kontan Delo mineral',
  },
  {
    id: 289,
    isFavourited: false,
    english: 'May I have Yogurt',
    creole: 'Mon ti a kontan Yogourt, Yaourt',
  },
  {
    id: 290,
    isFavourited: false,
    english: 'May I have Beer / ale',
    creole: 'Mon ti a kontan Labyer',
  },
  {
    id: 291,
    isFavourited: false,
    english: 'May I have Bread',
    creole: 'Mon ti a kontan Dipen',
  },
  {
    id: 292,
    isFavourited: false,
    english: 'May I have Jam',
    creole: 'Mon ti a kontan Konfitir',
  },
  {
    id: 293,
    isFavourited: false,
    english: 'How much is it and?',
    creole: 'Konbyen i koute?',
  },
  {
    id: 294,
    isFavourited: false,
    english: 'Why are they so expensive?',
    creole: 'Akoz sa i si ser?',
  },
  {
    id: 295,
    isFavourited: false,
    english: 'Could I have a...',
    creole: 'Mon ti a kontan gannyen...',
  },
  {
    id: 296,
    isFavourited: false,
    english: 'Do you have...?',
    creole: 'Eski ou annan...?',
  },
  {
    id: 297,
    isFavourited: false,
    english: 'How do you use...?',
    creole: 'Kote mon kapab gannyen?',
  },
  {
    id: 298,
    isFavourited: false,
    english: 'This is not working?',
    creole: 'Eski sa i pa mars?',
  },
  {
    id: 299,
    isFavourited: false,
    english: 'Is it got a guarantee...?',
    creole: 'Eski ou annan garanti...?',
  },
  {
    id: 300,
    isFavourited: false,
    english: 'It is not suitable',
    creole: 'I pa bon',
  },
  {
    id: 301,
    isFavourited: false,
    english: "I'm just looking?",
    creole: 'Mon pe zis gete',
  },
  {
    id: 302,
    isFavourited: false,
    english: 'Do you have this in my size?',
    creole: 'Eski ou annan sa dan mon tay?',
  },
  {
    id: 303,
    isFavourited: false,
    english: 'At what time do you open?',
    creole: 'Ki ler ou ouver?',
  },
  {
    id: 304,
    isFavourited: false,
    english: "I'd like to have a cough mixture",
    creole: 'Mon ti a kontan en siro la tou',
  },
  {
    id: 305,
    isFavourited: false,
    english: "I'd like to have a cream for sunburn",
    creole: 'Mon ti a kontan en lakrenm pour kou soley',
  },
  {
    id: 306,
    isFavourited: false,
    english: "I'd like to have a laxative",
    creole: 'Mon ti a kontan en laksatif',
  },
  {
    id: 307,
    isFavourited: false,
    english: "I'd like to have Adhesive plasters & cotton wool",
    creole: 'Mon ti a kontan Anplas ek lakoton',
  },
  {
    id: 308,
    isFavourited: false,
    english: "I'd like to have some aspirin",
    creole: 'Mon ti a kontan En bokou aspirin',
  },
  {
    id: 309,
    isFavourited: false,
    english: "I'd like to have an antiseptic cream",
    creole: 'Mon ti a kontan En lakrenm antiseptik',
  },
  {
    id: 310,
    isFavourited: false,
    english: "I'd like to have Something for insect cream",
    creole: 'Mon ti a kontan Keksoz pour pik moustik',
  },
  {
    id: 311,
    isFavourited: false,
    english: "I'd like to have Something against insect bites",
    creole: 'Mon ti a kontan En lakrenm pour piker zensek',
  },
  {
    id: 312,
    isFavourited: false,
    english: 'How is the weather today?',
    creole: 'Ki mannyer letan i ete ozordi?',
  },
  {
    id: 313,
    isFavourited: false,
    english: 'Today the weather is fine.',
    creole: 'Ozordi i fer bo.',
  },
  {
    id: 314,
    isFavourited: false,
    english: 'It is good weather, the sky is blue, we can see the sun',
    creole: 'I fer en bon letan, lesyel i ble, nou vwar soley i tape',
  },
  {
    id: 315,
    isFavourited: false,
    english: 'The sun is a-shining and there is no strong wind',
    creole: 'Soley i tape, pa tro divan',
  },
  {
    id: 316,
    isFavourited: false,
    english: 'Sometimes it rains',
    creole: 'I annan peryod lapli',
  },
  {
    id: 317,
    isFavourited: false,
    english: 'The sky is clouded and grey',
    creole: 'Lesyel i ranpli avek nyaz, letan i kouvert',
  },
  {
    id: 318,
    isFavourited: false,
    english: 'Occasionally, there is a thunder-and-lightning',
    creole: 'Tanzantan, i annan loraz ek zekler',
  },
  {
    id: 319,
    isFavourited: false,
    english: 'The climate is hot and humid',
    creole: 'I annan en klima so, e i annan bokou limidite avek en peryod fre',
  },
  {
    id: 320,
    isFavourited: false,
    english: 'What the temperature reaches about thirty degrees',
    creole: 'Kalite sala i tape, i fer apepre trant degre',
  },
  {
    id: 321,
    isFavourited: false,
    english: 'The rain can often fall/last at lot.',
    creole: 'I annan bokou lapli ki dire',
  },
  {
    id: 322,
    isFavourited: false,
    english:
      'There are two seasons in Seychelles: the northwest monsoon & the southeast monsoon',
    creole:
      'I annan de sezen Sesel, enn pandan moussoun nor-wes e lot pandan moussoun sid-es',
  },
  {
    id: 323,
    isFavourited: false,
    english:
      'During the rainy season, it will be better to have a light raincoat or a small fold-up umbrella for it is subject to sudden brief downpours',
    creole:
      'Pandan sezon lapli (gran sezon), i pli bon pour ou annan en lenpermeab leze parski i annan bann gro lapli ki tonbe en sel kou',
  },
  {
    id: 324,
    isFavourited: false,
    english: 'Do you speak English?',
    creole: 'Eski ou koz angle?',
  },
  {
    id: 325,
    isFavourited: false,
    english: "I don't speak Creole very well",
    creole: 'Pardon, mon pa tro koz byen Kreol',
  },
  {
    id: 326,
    isFavourited: false,
    english: 'I think I will learn Creole next year',
    creole: 'Mon panse mon pou aprann Kreol lannen prosen',
  },
  {
    id: 327,
    isFavourited: false,
    english: 'Is there someone who speaks English?',
    creole: 'Eski i annan en dimounn la ki koz Angle?',
  },
  {
    id: 328,
    isFavourited: false,
    english: 'Can you speak more slowly please?',
    creole: 'Ou kapab koz en pti pe pli douman silvouple?',
  },
  {
    id: 329,
    isFavourited: false,
    english: 'Why do you ask me that?',
    creole: 'Akoz ou demande mwan sa?',
  },
  {
    id: 330,
    isFavourited: false,
    english: 'Can you show me how to get there?',
    creole: 'Montre mwan ki mannyer mon ariv kot ou reste?',
  },
  {
    id: 331,
    isFavourited: false,
    english: 'Is there a US Embassy in Victoria?',
    creole: 'Eski i annan anbasad Ameriken dan Viktorya?',
  },
  {
    id: 332,
    isFavourited: false,
    english: 'Police here please! Call a doctor / the police.',
    creole: 'Ed mwan silvouple, demann en dokter / lapolis',
  },
  {
    id: 333,
    isFavourited: false,
    english: 'Where can we find something to eat?',
    creole: 'Kote nou kapab rod en manze?',
  },
  {
    id: 334,
    isFavourited: false,
    english: 'What is there to eat?',
    creole: 'Ki i annan pour manze?',
  },
  {
    id: 335,
    isFavourited: false,
    english: 'I feel sick, I am hot',
    creole: 'Mon santi mon malad, mon ganny so',
  },
  {
    id: 336,
    isFavourited: false,
    english: 'What restaurant would you recommend?',
    creole: 'Ki restoran ou ti a rekomande?',
  },
  {
    id: 337,
    isFavourited: false,
    english: 'Wait for me there',
    creole: 'Esper mwan laba',
  },
  {
    id: 338,
    isFavourited: false,
    english: 'There are two restaurants on the coast',
    creole: 'I annan de restoran lo borlanmer',
  },
  {
    id: 339,
    isFavourited: false,
    english: 'They are not open this week',
    creole: 'Zot pa ouver sa semenn',
  },
  {
    id: 340,
    isFavourited: false,
    english: 'There is a path to the beach, by the sea',
    creole: 'I annan en pti semen ki pas lo lans',
  },
  {
    id: 341,
    isFavourited: false,
    english: "Let's go for a walk.",
    creole: 'Anou fer en pti promnad.',
  },
  {
    id: 342,
    isFavourited: false,
    english: "You must hurry, we don't have much time",
    creole: 'Vini fe vit-al-despota, nou pa annan bokou letan',
  },
  {
    id: 343,
    isFavourited: false,
    english: 'I prefer to take the car',
    creole: 'Mon prefer pran loto',
  },
  {
    id: 344,
    isFavourited: false,
    english: 'The car has broken down',
    creole: 'Machin in kase',
  },
  {
    id: 345,
    isFavourited: false,
    english: 'We may be too late to get a flight',
    creole: 'Petet nou an retar, nou pa pou ganny sa vol',
  },
  {
    id: 346,
    isFavourited: false,
    english: 'The garage has run out of spare',
    creole: 'Garaz napa pyes',
  },
  {
    id: 347,
    isFavourited: false,
    english: 'Goodness knows what to do',
    creole: 'Bondye konnen ki pour fer',
  },
  {
    id: 348,
    isFavourited: false,
    english: 'I am on holiday',
    creole: 'Mon an konze',
  },
  {
    id: 349,
    isFavourited: false,
    english: 'It is difficult to follow me?',
    creole: 'Eski i difisil pour swiv mwan?',
  },
  {
    id: 350,
    isFavourited: false,
    english: 'He will be back next week',
    creole: 'I pou retournen semenn prosen',
  },
  {
    id: 351,
    isFavourited: false,
    english: 'We are sure to become good friends',
    creole: 'Nou pou sirman vin bon zanmi',
  },
  {
    id: 352,
    isFavourited: false,
    english: 'They all became big friends',
    creole: 'Zot tou zot in vin gran zanmi',
  },
];
